{% set name = "sporco" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ec8bb48e897738b20e42fffabae450a16d997f6f0ed182cc81985e3db11fe150

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - future
    - python
    - setuptools
    - pip
    - numpy >=1.12
    - scipy >=0.13.3
    - imageio
    - pytest-runner
  run:
    - future
    - python
    - numpy >=1.12
    - scipy >=0.13.3
    - imageio
    - matplotlib-base >=1.3.1
    - pyfftw >=0.10.4

test:
  imports:
    - sporco
    - sporco.util
    - sporco.linalg

about:
  home: https://github.com/bwohlberg/sporco
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Sparse Optimisation Research Code: A Python package for sparse coding and dictionary learning'
  description: |
    SPORCO is a Python package for solving optimisation problems with
    sparsity-inducing regularisation. These consist primarily of sparse
    coding and dictionary learning problems, including convolutional
    sparse coding and dictionary learning, but there is also support for
    other problems such as Total Variation regularisation and Robust
    PCA. The optimisation algorithms in the current version are based
    on the Alternating Direction Method of Multipliers (ADMM) or on
    the Proximal Gradient Method (PGM).
  doc_url: https://sporco.readthedocs.io/en/latest/
  dev_url: https://github.com/bwohlberg/sporco

extra:
  recipe-maintainers:
    - bwohlberg
