appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: RQN1xUeAwi9a4UMNom/JrmEa1FcoMqEawKLSoOGAGtO7rOC1raw3S9vPwH7zb2U0UBGZBJap4aqTM857wJQsAZkElW2TK8I4m/ASclzj3LjSA/83xTTOC1z9T+/zkkdUR8JKJSMcLyM1cUN11JjrUK46hM58+GfNmQd7Fg2FCNobSWbUscFVIEOFdmxPTGccqH7UuMaY5Rl+qELLjx8v920kzFX+EhMPHuGTSgjQDvH5kUZPvERB2VVjmcic/79nCC+/on34dDnnFj7lOctSS03cBnKzMZgusflzD/i3wsE4s/WSV2vv7Q7cz6n3OBXbpLI7c71r3LCFWMBGPxw+nuBXUymWT+tzK6tVpDETQodN6iC4oo1KnIgHOvUm3a7YXUoi/7iYmc9fTpk8tcIJxLBpch4jzO08Ni6iOTjEzwspmbi78UyUt3Yuy9n6AIqC9gME0KS9/0ynjSqEGuk1fEgpSiWKeLiX73N5g+YN8owz/HTh1tfeBPXX3aTwzstMEVdy5mP/ijJJysCYWw54pQ50eV0WFQnUJ8BDvxclfFwV1XIDgQRscBimjUr+G4nnCbrl9N4yZ+gohUZdW/9xwJnlqq4kwm5dLEdHVLEsV++C1AT8mHHX+jqrC1jZ1OEHDWXuYnNXy2RBCNZsxnWNjX1Tig3EzBiMkPwgvbGouP8=}
provider:
  win: azure
conda_forge_output_validation: true
